from pathlib import Path
p=Path('college-acceptance.js')
s=p.read_text()
s=s.replace("const VERSION='20260815-college-acceptance-v4-floating-halo';","const VERSION='20260815-college-acceptance-v5-floating-cutout';")
old="""function trimLogo(img){const iw=img.naturalWidth||img.width||1,ih=img.naturalHeight||img.height||1;const src=document.createElement('canvas');src.width=iw;src.height=ih;const c=src.getContext('2d',{willReadFrequently:true});c.drawImage(img,0,0,iw,ih);let d;try{d=c.getImageData(0,0,iw,ih).data;}catch(_){return src;}const border=(x,y)=>{const i=(y*iw+x)*4,r=d[i],g=d[i+1],b=d[i+2],a=d[i+3];return a<18||(r>246&&g>246&&b>246);};let l=0,r=iw-1,t=0,b=ih-1;const row=y=>{let n=0;for(let x=l;x<=r;x++)if(border(x,y))n++;return n/Math.max(1,r-l+1)>.985;};const col=x=>{let n=0;for(let y=t;y<=b;y++)if(border(x,y))n++;return n/Math.max(1,b-t+1)>.985;};while(t<b&&row(t))t++;while(b>t&&row(b))b--;while(l<r&&col(l))l++;while(r>l&&col(r))r--;const w=Math.max(1,r-l+1),h=Math.max(1,b-t+1),out=document.createElement('canvas');out.width=w;out.height=h;out.getContext('2d').drawImage(src,l,t,w,h,0,0,w,h);return out;}"""
new="""function trimLogo(img){const iw=img.naturalWidth||img.width||1,ih=img.naturalHeight||img.height||1;const src=document.createElement('canvas');src.width=iw;src.height=ih;const c=src.getContext('2d',{willReadFrequently:true});c.drawImage(img,0,0,iw,ih);let id;try{id=c.getImageData(0,0,iw,ih);}catch(_){return src;}const d=id.data,seen=new Uint8Array(iw*ih),q=[],isBg=(x,y)=>{const i=(y*iw+x)*4,r=d[i],g=d[i+1],b=d[i+2],a=d[i+3];return a<18||(r>242&&g>242&&b>242&&Math.max(r,g,b)-Math.min(r,g,b)<10);};const push=(x,y)=>{if(x<0||y<0||x>=iw||y>=ih)return;const k=y*iw+x;if(seen[k]||!isBg(x,y))return;seen[k]=1;q.push(k);};for(let x=0;x<iw;x++){push(x,0);push(x,ih-1);}for(let y=0;y<ih;y++){push(0,y);push(iw-1,y);}for(let qi=0;qi<q.length;qi++){const k=q[qi],x=k%iw,y=(k/iw)|0;push(x+1,y);push(x-1,y);push(x,y+1);push(x,y-1);}for(let k=0;k<seen.length;k++)if(seen[k])d[k*4+3]=0;c.putImageData(id,0,0);let l=iw,r=-1,t=ih,b=-1;for(let y=0;y<ih;y++)for(let x=0;x<iw;x++){const a=d[(y*iw+x)*4+3];if(a>12){if(x<l)l=x;if(x>r)r=x;if(y<t)t=y;if(y>b)b=y;}}if(r<l||b<t)return src;const pad=2;l=Math.max(0,l-pad);t=Math.max(0,t-pad);r=Math.min(iw-1,r+pad);b=Math.min(ih-1,b+pad);const w=r-l+1,h=b-t+1,out=document.createElement('canvas');out.width=w;out.height=h;out.getContext('2d').drawImage(src,l,t,w,h,0,0,w,h);return out;}"""
if old not in s: raise SystemExit('trimLogo target not found')
s=s.replace(old,new)
old2="""function drawLogo(ctx,p=1){if(!S.logo)return;const t=Math.max(0,Math.min(1,p)),e=1-Math.pow(1-t,3);const art=S.logoTrim||S.logo,iw=art.width||art.naturalWidth||1,ih=art.height||art.naturalHeight||1;const targetBottom=887,shoulderTop=Math.max(500,Math.min(690,S.shoulderY||560)),safeGap=8,availableH=Math.max(90,targetBottom-shoulderTop-safeGap),maxArtW=930,maxArtH=Math.max(60,availableH),sc=Math.min(maxArtW/iw,maxArtH/ih),aw=iw*sc,ah=ih*sc,finalY=targetBottom-ah/2,startY=95,x=540,y=startY+(finalY-startY)*e;ctx.save();ctx.translate(x,y);ctx.save();ctx.globalAlpha=.42;ctx.shadowColor='rgba(255,255,255,.95)';ctx.shadowBlur=52;ctx.shadowOffsetX=0;ctx.shadowOffsetY=0;ctx.drawImage(art,-aw/2,-ah/2,aw,ah);ctx.restore();ctx.save();ctx.globalAlpha=.72;ctx.shadowColor='rgba(255,255,255,.95)';ctx.shadowBlur=24;ctx.shadowOffsetX=0;ctx.shadowOffsetY=0;ctx.drawImage(art,-aw/2,-ah/2,aw,ah);ctx.restore();ctx.save();ctx.shadowColor='rgba(2,18,40,.34)';ctx.shadowBlur=12;ctx.shadowOffsetY=5;ctx.drawImage(art,-aw/2,-ah/2,aw,ah);ctx.restore();ctx.drawImage(art,-aw/2,-ah/2,aw,ah);ctx.restore();}"""
new2="""function drawLogo(ctx,p=1){if(!S.logo)return;const t=Math.max(0,Math.min(1,p)),e=1-Math.pow(1-t,3);const art=S.logoTrim||S.logo,iw=art.width||art.naturalWidth||1,ih=art.height||art.naturalHeight||1;const targetBottom=887,shoulderTop=Math.max(500,Math.min(690,S.shoulderY||560)),safeGap=8,availableH=Math.max(90,targetBottom-shoulderTop-safeGap),maxArtW=930,maxArtH=Math.max(60,availableH),sc=Math.min(maxArtW/iw,maxArtH/ih),aw=iw*sc,ah=ih*sc,finalY=targetBottom-ah/2,startY=95,x=540,y=startY+(finalY-startY)*e;ctx.save();ctx.translate(x,y);ctx.save();ctx.globalAlpha=.62;ctx.shadowColor='rgba(255,255,255,1)';ctx.shadowBlur=70;ctx.drawImage(art,-aw/2,-ah/2,aw,ah);ctx.restore();ctx.save();ctx.globalAlpha=.92;ctx.shadowColor='rgba(255,255,255,1)';ctx.shadowBlur=32;ctx.drawImage(art,-aw/2,-ah/2,aw,ah);ctx.restore();ctx.save();ctx.shadowColor='rgba(0,10,28,.50)';ctx.shadowBlur=18;ctx.shadowOffsetY=8;ctx.drawImage(art,-aw/2,-ah/2,aw,ah);ctx.restore();ctx.drawImage(art,-aw/2,-ah/2,aw,ah);ctx.restore();}"""
if old2 not in s: raise SystemExit('drawLogo target not found')
s=s.replace(old2,new2)
p.write_text(s)
