from pathlib import Path
p=Path('csms-template-recovery-v1.js')
s=p.read_text()

s=s.replace("const VERSION='20260815-welcome-original-restored-v1';","const VERSION='20260815-welcome-athlete-main-drive-v2';",1)

anchor="function normalizeAthleteRecord(item){if(!item)return null;return {...item,id:item.id||'',first:item.first||item.firstName||'',last:item.last||item.lastName||'',year:item.year||item.classYear||item.graduationYear||'',heroBlob:item.heroBlob||item.heroImage||null};}\n"
insert=anchor+"""function welcomeBase64ToBlob(base64,mimeType){const binary=atob(base64);const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return new Blob([bytes],{type:mimeType||'image/png'});}\nasync function welcomeBridgeCall(action,payload={}){if(typeof window.csmsAuthenticatedBridgeCall!=='function'&&typeof csmsAuthenticatedBridgeCall!=='function')throw new Error('Google Drive Bridge is unavailable. Refresh Studio and connect Google Drive.');const call=window.csmsAuthenticatedBridgeCall||csmsAuthenticatedBridgeCall;const ensure=window.csmsEnsureAuthenticatedBridge||((typeof csmsEnsureAuthenticatedBridge==='function')?csmsEnsureAuthenticatedBridge:null);if(ensure)await Promise.race([ensure({userInitiated:true}),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Google Drive connection timed out.')),12000))]);return await Promise.race([call(action,payload,{userInitiated:true}),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Google Drive did not respond to '+action+' within 20 seconds.')),20000))]);}\nasync function getAthleteMainSavedCards(){const result=await welcomeBridgeCall('listSavedCards',{});if(!result||!result.ok)throw new Error(result&&result.error?result.error:'Drive Saved Cards library is unavailable');return (Array.isArray(result.cards)?result.cards:[]).filter(card=>{const type=String(card.cardType||card.type||'').toUpperCase();const name=String(card.name||'').toUpperCase();return type==='ATHLETE HEADSHOT CARD'||name.includes('ATHLETE HEADSHOT CARD');}).map(card=>({id:String(card.fileId||card.id||''),fileId:String(card.fileId||card.id||''),first:card.first||'',last:card.last||'',year:String(card.classLine||'').replace(/[^0-9]/g,'')||'',classLine:card.classLine||'',name:card.name||'Athlete Main Headshot',source:'drive-athlete-main'})).filter(card=>card.fileId);}\nasync function getAthleteMainSavedCardBlob(fileId){const result=await welcomeBridgeCall('getSavedCard',{fileId});if(!result||!result.ok||!result.card||!result.card.data)throw new Error('Athlete Main Headshot card could not be loaded from Drive');return welcomeBase64ToBlob(result.card.data,result.card.mimeType||'image/png');}\n"""
if anchor not in s: raise SystemExit('normalize anchor not found')
s=s.replace(anchor,insert,1)

s=s.replace('<div class="notice">Launch this template from the Template Library, choose any available saved Hero Card below, then save or export as an image or video. The Hero Card itself is never rebuilt or changed.</div>','<div class="notice">Launch this template from the Template Library, choose a saved Athlete Main Headshot card below, then save or export as an image or video. The Athlete Main Headshot card itself is never rebuilt or changed.</div>',1)
s=s.replace('<div class="control"><label for="welcomeHeroSelect">Available Hero Cards</label><select id="welcomeHeroSelect"><option value="">Select an available Hero Card</option></select></div>','<div class="control"><label for="welcomeHeroSelect">Athlete Main Headshot Cards</label><select id="welcomeHeroSelect"><option value="">Select an Athlete Main Headshot card</option></select></div>',1)
s=s.replace("<div id=\"welcomeStatus\" class=\"status\">Choose a saved Hero Card.</div>","<div id=\"welcomeStatus\" class=\"status\">Choose an Athlete Main Headshot card.</div>",1)

old_refresh="async function refreshWelcomeHeroChoices(preferredId=''){\n  const e=welcomeEls();if(!e.select)return[];try{const records=await getUnifiedAthletesCompat();welcomeHeroRecords=records.filter(item=>item&&item.heroBlob);const previous=preferredId||e.select.value;e.select.innerHTML='<option value=\"\">Select an available Hero Card</option>';welcomeHeroRecords.forEach(item=>{const opt=document.createElement('option');opt.value=item.id;opt.textContent=`${item.first||''} ${item.last||''} — Class of ${item.year||'—'}`.trim();e.select.appendChild(opt);});if(previous&&welcomeHeroRecords.some(x=>x.id===previous))e.select.value=previous;if(!welcomeHeroRecords.length)e.status.textContent='No available Hero Cards found. Create and save a Hero Card first.';return welcomeHeroRecords;}catch(err){e.status.textContent=`Could not load Hero Cards: ${err.message}`;return[];}\n}\n"
new_refresh="async function refreshWelcomeHeroChoices(preferredId=''){\n  const e=welcomeEls();if(!e.select)return[];const previous=preferredId||e.select.value;e.select.innerHTML='<option value=\"\">Loading Athlete Main Headshot cards…</option>';e.select.disabled=true;try{welcomeHeroRecords=await getAthleteMainSavedCards();welcomeHeroRecords.sort((a,b)=>String(a.last||'').localeCompare(String(b.last||''))||String(a.first||'').localeCompare(String(b.first||'')));e.select.innerHTML='<option value=\"\">Select an Athlete Main Headshot card</option>';welcomeHeroRecords.forEach(item=>{const opt=document.createElement('option');opt.value=item.fileId;const athlete=`${item.first||''} ${item.last||''}`.trim();opt.textContent=athlete||(String(item.name||'Athlete Main Headshot').replace(/\\.png$/i,''));e.select.appendChild(opt);});if(previous&&welcomeHeroRecords.some(x=>x.fileId===previous))e.select.value=previous;if(!welcomeHeroRecords.length)e.status.textContent='No Athlete Main Headshot cards found in Google Drive. Save an Athlete Main Headshot card first.';else e.status.textContent='Choose an Athlete Main Headshot card.';return welcomeHeroRecords;}catch(err){welcomeHeroRecords=[];e.select.innerHTML='<option value=\"\">Select an Athlete Main Headshot card</option>';e.status.textContent=`Could not load Athlete Main Headshot cards: ${err.message}`;return[];}finally{e.select.disabled=false;}\n}\n"
if old_refresh not in s: raise SystemExit('refresh function not found')
s=s.replace(old_refresh,new_refresh,1)

old_load="async function loadWelcomeHero(id){const e=welcomeEls(),record=welcomeHeroRecords.find(item=>item.id===id);if(!record||!record.heroBlob){welcomeHeroImage=null;drawWelcomeCard();return;}const url=URL.createObjectURL(record.heroBlob),img=new Image();img.onload=()=>{welcomeHeroImage=img;welcomeDropProgress=1;e.project.value=`Welcome Aboard — ${record.first||''} ${record.last||''}`.trim();drawWelcomeCard();e.status.textContent=`Using locked Hero Card: ${record.first||''} ${record.last||''}`.trim();setTimeout(()=>URL.revokeObjectURL(url),60000);};img.onerror=()=>{URL.revokeObjectURL(url);e.status.textContent='Could not open the saved Hero Card.';};img.src=url;}\n"
new_load="async function loadWelcomeHero(id){const e=welcomeEls(),record=welcomeHeroRecords.find(item=>item.fileId===id||item.id===id);if(!record){welcomeHeroImage=null;drawWelcomeCard();return;}e.status.textContent='Loading Athlete Main Headshot card…';try{const blob=await getAthleteMainSavedCardBlob(record.fileId||record.id),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{welcomeHeroImage=img;welcomeDropProgress=1;const athlete=`${record.first||''} ${record.last||''}`.trim();e.project.value=athlete?`Welcome Aboard — ${athlete}`:'Welcome Aboard — Untitled';drawWelcomeCard();e.status.textContent=athlete?`Using Athlete Main Headshot: ${athlete}`:'Using Athlete Main Headshot card.';setTimeout(()=>URL.revokeObjectURL(url),60000);};img.onerror=()=>{URL.revokeObjectURL(url);e.status.textContent='Could not open the Athlete Main Headshot card.';};img.src=url;}catch(err){welcomeHeroImage=null;drawWelcomeCard();e.status.textContent=`Could not load Athlete Main Headshot card: ${err.message}`;}}\n"
if old_load not in s: raise SystemExit('load function not found')
s=s.replace(old_load,new_load,1)

s=s.replace("ctx.fillText('Select an available Hero Card',540,675);","ctx.fillText('Select an Athlete Main Headshot card',540,675);",1)
s=s.replace("if(!welcomeHeroImage){e.status.textContent='Choose a saved Hero Card first.';return;}","if(!welcomeHeroImage){e.status.textContent='Choose an Athlete Main Headshot card first.';return;}")

p.write_text(s)
print('updated', p)
